import { type NextPage } from "next";
import Head from "next/head";
import { HeroTitle } from "~/components/hero/HeroTitle";
import { NavHeader } from "~/components/layout/NavHeader";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RealtyWatch</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader isHero />
      <HeroTitle />
    </>
  );
};

export default Home;
